FROM node:22.11.0-alpine3.20 AS base

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev --no-audit --no-fund && npm cache clean --force

COPY server ./server

ENV NODE_ENV=production
ENV PORT=3001
ENV NODE_OPTIONS=--max-old-space-size=256

# Create non-root user
RUN adduser -D -H -u 10102 appuser && chown -R appuser:appuser /app
USER 10102:10102

EXPOSE 3001

CMD ["node", "server/index.js"]

