version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - NODE_ENV=production
      - PORT=3001
      - WEB_ORIGIN=http://localhost:8080
      # - SENTRY_DSN=your_sentry_dsn_here
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - REDDIT_USERNAME
      - REDDIT_PASSWORD
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      api:
        condition: service_healthy
    environment:
      # Used by Vite to initialize Sentry in frontend if set at build time
      # - VITE_SENTRY_DSN=your_sentry_dsn_here
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 5
