name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm run build
      - name: Build API image
        run: docker build -t sizeseeker-api -f Dockerfile.api .
      - name: Build Web image
        run: docker build -t sizeseeker-web -f Dockerfile.web .

